# Generated by Django 4.2.9 on 2024-07-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuppy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uppyusercredentials',
            name='Avatar',
            field=models.ImageField(default='Uploads_from_User/profile/avatar/person-circle.svg', upload_to='users/avatar'),
        ),
    ]
